# Generated by Django 5.0.4 on 2024-06-16 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='carrer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_carrera_id', to='api.career'),
        ),
    ]
